name: Weekly backup
on:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: backup
        run: cp rrt.json ./backup/rrt-$(date '+%d-%m-%Y').json
      - uses: stefanzweifel/git-auto-commit-action@v4
        file_pattern: ./backup/*.json
        with:
          commit_message: weekly backup - $(date '+%d-%m-%Y')
