name: Run parser
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update-json:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno run --allow-all ./sheet-to-json.ts
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
      - name: get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(TZ=":Asia/Kolkata" date)"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: rrt.json
          commit_message: data updated on - ${{ steps.timestamp.outputs.timestamp }}
