name: Run parser
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-json:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno run --allow-all ./sheet-to-json.ts
      - uses: stefanzweifel/git-auto-commit-action@v4
        file_pattern: rrt.json
        with:
          commit_message: data updated on - $(TZ=":Asia/Kolkata" date)
